# Generated by Django 4.0.5 on 2022-06-18 07:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gameDB', '0002_remove_difficulty_game_id_alter_difficulty_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='gameDB.difficulty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='label',
            field=models.CharField(max_length=10),
        ),
    ]
