# Generated by Django 4.0.5 on 2022-06-18 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameDB', '0003_game_difficulty_alter_difficulty_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gameDB.difficulty'),
        ),
    ]
