# Generated by Django 4.0.5 on 2022-06-18 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameDB', '0006_difficulty_game_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='difficulty',
            name='game_id',
        ),
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gameDB.difficulty'),
            preserve_default=False,
        ),
    ]
