# Generated by Django 4.0.5 on 2022-06-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameDB', '0007_remove_difficulty_game_id_game_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='difficulty',
        ),
        migrations.DeleteModel(
            name='Difficulty',
        ),
    ]
