# Generated by Django 4.0.5 on 2022-06-18 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameDB', '0008_remove_game_difficulty_delete_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameDB.game')),
            ],
        ),
    ]
