# Generated by Django 4.0.5 on 2022-06-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameDB', '0009_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Difficulty',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
