# Generated by Django 4.0.4 on 2022-05-10 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameDB', '0002_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 11, 55, 48, 984102)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='images/default_profile_pic.png', upload_to='images/'),
        ),
    ]
