# Generated by Django 4.0.4 on 2022-05-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameDB', '0004_difficulty_game_delete_score_difficulty_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
