# Generated by Django 4.0.4 on 2022-05-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameDB', '0005_alter_game_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.IntegerField(blank=True),
        ),
    ]
