# Generated by Django 4.0.4 on 2022-05-30 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameDB', '0008_alter_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='won',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
